#!/bin/bash

if [ ! -e /etc/setup ]
then
	/opt/setup
	touch /etc/setup
fi

mkdir /run/dbus

chown root:x11 /tmp/.X11-unix/X*
chmod 660 /tmp/.X11-unix/X*

chown root:wayland /tmp/wayland-0
chmod 660 /tmp/wayland-0

chmod 777 /tmp/trasfer

dbus-daemon --system

/sbin/sshd -D

