#!/bin/bash

. /host/etc/bashrc

export XDG_RUNTIME_DIR=/tmp/$UID
export PIPEWIRE_RUNTIME_DIR=/tmp

export DISPLAY=$(cat /tmp/.X11-unix/display)
export WAYLAND_DISPLAY=wayland-0

if [ ! $UID -eq '0' ]
then
	if [ ! -d $XDG_RUNTIME_DIR ]
	then
		mkdir -m 0700 $XDG_RUNTIME_DIR
		pipewire-pulse &> /dev/null&
	fi

	eval $(ssh-agent) &> /dev/null
	eval $(dbus-launch)
	ssh-add ~/.ssh/* &> /dev/null
	pipewire-pulse &> /dev/null &

	ln -sf /tmp/wayland-0 $XDG_RUNTIME_DIR/
fi
