#!/bin/bash

if [ ! -e /etc/setup ]
then
	/opt/setup
	touch /etc/setup
fi

XDISPLAY=$(cat /tmp/.X11-unix/display)

chown root:x11 /tmp/.X11-unix/xauth
chmod 660 /tmp/.X11-unix/xauth

chown root:x11 /tmp/.X11-unix/X$XDISPLAY
chmod 660 /tmp/.X11-unix/X$XDISPLAY

chown root:wayland /tmp/wayland-0
chmod 660 /tmp/wayland-0

chmod 777 /tmp/trasfer

mkdir /run/dbus
dbus-daemon --system

/sbin/sshd -De

sleep inf
